apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: test
data:
  database_url: mongodb-service
  # The URL for MongoDB service. This should match the service name and port.
