# MongoDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: test
type: Opaque
data:
  mongodb-username: dXNlcm5hbWU= # Decodes to "username"
  mongodb-password: cGFzc3dvcmQ= # Decodes to "password"
  mongo-web-username: YWRtaW4= # this is to access the Front end server
  mongo-web-password: YWRtaW4xMjM0NTY3ODkxMA== #this is to access the Front end server
