#https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.1/deploy/static/provider/cloud/deploy.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pathbased-ingress
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # Disable SSL redirect for HTTP traffic
    nginx.ingress.kubernetes.io/use-regex: "true" # Enable regex in paths
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # Rewrite the URL path to remove the prefix
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:

      - path: /nginx(/|$)(.*) # Match /nginx and /nginx/anything
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-clusterip #Provide the Services name Which we want to expose 
            port:
              number: 80

      - path: /httpd(/|$)(.*) # Match /httpd and /httpd/anything
        pathType: ImplementationSpecific
        backend:
          service:
            name: httpd-clusterip #Provide the Services name Which we want to expose 
            port:
              number: 80

      - path: /(.*) # Match everything else
        pathType: ImplementationSpecific
        backend:
          service:
            name: httpd-clusterip #Provide the Services name Which we want to expose 
            port:
              number: 80
